---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-sa
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-rolebinding
subjects:
  - kind: ServiceAccount
    name: deployment-sa
    namespace: jenkins
roleRef:
  kind: ClusterRole
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io
